// openDb: opens the SQLite file, applies pragmas and pending migrations, and builds the repositories.
// See docs/architecture/storage.md.

import { Database } from 'bun:sqlite'
import { fileURLToPath } from 'node:url'
import { KeithError } from '@keith/sdk'
import { drizzle } from 'drizzle-orm/bun-sqlite'
import { migrate } from 'drizzle-orm/bun-sqlite/migrator'
import { createAuthTokensRepository, createNodesRepository } from './access.ts'
import { createMemoriesRepository } from './memories.ts'
import { createMessagesRepository } from './messages.ts'
import type { Orm } from './orm.ts'
import { createPersonsRepository, createRelationshipsRepository } from './persons.ts'
import { createPluginDataRepository } from './plugin-data.ts'
import { createThreadsRepository } from './threads.ts'
import type { Db, Repositories } from './types.ts'
import { createCommitmentsRepository, createDeliveriesRepository, createTasksRepository } from './work.ts'

/** Generated by drizzle-kit from schema.ts (packages/core/drizzle). */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url))

/** Opens (creating if needed) the database at `path` and applies pending migrations. */
export function openDb(path: string): Db {
  const sqlite = new Database(path, { create: true, strict: true })
  try {
    sqlite.run('PRAGMA journal_mode = WAL')
    sqlite.run('PRAGMA foreign_keys = ON')
    sqlite.run('PRAGMA busy_timeout = 5000')
    const orm = drizzle({ client: sqlite })
    migrate(orm, { migrationsFolder: MIGRATIONS_FOLDER })
    return {
      path,
      repos: createRepositories(orm),
      close: () => sqlite.close(),
    }
  } catch (cause) {
    sqlite.close()
    throw new KeithError('INTERNAL', 'database open failed', { cause, details: { path } })
  }
}

function createRepositories(db: Orm): Repositories {
  return {
    persons: createPersonsRepository(db),
    relationships: createRelationshipsRepository(db),
    authTokens: createAuthTokensRepository(db),
    nodes: createNodesRepository(db),
    threads: createThreadsRepository(db),
    messages: createMessagesRepository(db),
    tasks: createTasksRepository(db),
    commitments: createCommitmentsRepository(db),
    deliveries: createDeliveriesRepository(db),
    memories: createMemoriesRepository(db),
    pluginData: createPluginDataRepository(db),
  }
}
